In [2]:
import numpy as np

^np is an alias.  always do it this way

diff between list and array:
arrays have to be all the same data type (aka homogenous)
lists are a collection of pointers to different objects in memory
arrays point to a single location in memory
this results in speed increase

helps us eliminate for loops via broadcasting and vectorization

In [ ]:
list1 = ["sanjay",12, [5, 6, 7], {}, "sammi"]
np.array([1, 2, 3, 4, 5, 6])

.array() is a method of the numpy.ndarray class, ndarray object

In [4]:
array1 = np.array([1, 2, 3, 4, 5, 6])  #passed a python list into an array. can also pass tuple.
print(array1)
print(type(array1))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


Dimensions in Arrays

In [5]:
#0-D arrays, these are also called Scalars
array2 = np.array(42)

#1-D arrays.  They have 0-D arrays as the elements.  These are the most basic and common arrays
array3 = np.array([1, 2, 3, 4, 5, 6])

#2-D array.  These arrays contain 1-D arrays as the elements. They signify the matrix
array4 = np.array([[1, 2, 3], [4, 5, 6]])
print(array4)

#3-D array. They contain 2-D arrays as the elements. 
array5 = np.array([[[1, 2, 3], [4, 5, 6]],[[1, 2, 3], [4, 5, 6]]])
print(array5)

[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [7]:
print(array2.ndim)  #.ndim is a class attribute (not a method)
print(array3.ndim)  # tells us how many dimensions our array has
print(array4.ndim)
print(array5.ndim)

0
1
2
3


In [13]:
print(array4[0])
print(array4[1])
print(array4[0] + array4[1])
print(array4.ndim)
new_array = array4[0] + array4[1]
print(new_array.ndim)

[1 2 3]
[4 5 6]
[5 7 9]
2
1


since both elements above are arrays of 3 elements you can add them.  if one array was 4 elements and the other was 3 then you couldn't add them.

In [16]:
#Slicing is similar to python lists
array6 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(array6[0:3])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Arthimetic Operations

We can perform element-wise operations with scalar values

In the below example numpy performs "stretching" to change the values of the array.  numpy doesnt make a new array of the new values
[1, 1, 1, 1, 1, 1, 1]

In [18]:
total = array3 + 1
print(array3)
print(total)

[1 2 3 4 5 6]
[2 3 4 5 6 7]


In [20]:
product = array3 * 2
division = array3 / 2
print(product)
print(division)

[ 2  4  6  8 10 12]
[0.5 1.  1.5 2.  2.5 3. ]


Aggregate Funcations
-min
-max
-mean
-sum

In [26]:
print(array3)
total = np.sum(array3)
lowest = np.min(array3)
highest = np.max(array3)
average = np.mean(array3)
print(total, lowest, highest, average)

print(array3.sum())
print(array3.min())
print(array3.max())
print(array3.mean())


[1 2 3 4 5 6]
21 1 6 3.5
21
1
6
3.5


In [29]:
#Broadcasting with a 2D array
print(array6)
multidimension_broadcast = array6 * 2
print(multidimension_broadcast)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]
 [20 22 24]]


Shaping with Numpy Arrays
-attribute called shape

returns a tuple which means they can't be changed.  order and size matters
the numbers returned form the shape of the matrix (not to be confused with the dimensions of the arrays)
the shape has to always be a rectange or a square.  so that means each element needs to have an equal number of other elements
4 4 4 4
4 4 4 4
1 2 5 6

not valid:
3 2 5
4 4 7
1 3 5 3

In [30]:
print(array6.shape) 
print(array5.shape) 

(4, 3)
(2, 2, 3)


In [37]:
#Reshaping Arrays
#when reshaping you need to have a number of total elements so that the new shape is divisible 6 = 3,2
print(array3)
print(array3.shape) #(6,) because its a 1-D array
print(np.reshape(array3, (3,2)))   
print(array3.reshape(3,2)) #same as above. this is a ndarray method.  above is a numpy function

[1 2 3 4 5 6]
(6,)
[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]


Transposing Arrays 

default argument = reverses the order of the axises

In [41]:
print(array6)
print(array6.transpose())

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


Boolean Operations

In [47]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([2, 2, 3, 3, 5])
c = a == b
print(c)

d = np.array([True, True, False, False])
e = np.array([False, True, True, False])
f = np.logical_and(d, e)
print(f)
g = np.logical_or(d, e)
print(g)
h = np.array_equal(d, e) #only true if both arrays are exactly the same
print(h)

[False  True  True False  True]
[False  True False False]
[ True  True  True False]
False


Sorting

In [56]:
i = np.array([3, 10, 14, 4, 6, 3, 99, 87, 8])
print(i)
j = np.sort(i)
print(j)  #sorted in ascending order
k = np.sort(i)[::-1]  #sorted in descending order
print(k)
i.sort() #sort method will change the original method
print(i)


[ 3 10 14  4  6  3 99 87  8]
[ 3  3  4  6  8 10 14 87 99]
[99 87 14 10  8  6  4  3  3]
[ 3  3  4  6  8 10 14 87 99]
